language: java

jdk:
 - oraclejdk11

env:
 - MAVEN_VERSION=3.3.9

services:
 - docker

addons:
 sonarcloud:
  organization: "tomdatbenik" # the key of the org you chose at step #
  
install:
 - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"

script:
 - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=Tomdatbenik_Collapporation-Backend
 #Copy lines for a new subfolder to build and push dockerfile
 - cd Eureka
 - mvn clean install
 - docker build -t docker.io/$DOCKER_NAME/collaporation-eureka:latest .
 #End of needed copy
 #Copy lines for a new subfolder to build and push dockerfile
 - cd ../Gateway
 - mvn clean install
 - docker build -t docker.io/$DOCKER_NAME/collaporation-gateway:latest .
 #End of needed copy
 #Copy lines for a new subfolder to build and push dockerfile
 - cd ../token
 - mvn clean install
 - docker build -t docker.io/$DOCKER_NAME/collaporation-token:latest .
 #End of needed copy
 #Copy lines for a new subfolder to build and push dockerfile
 - cd ../UserService
 - mvn clean install
 - docker build -t docker.io/$DOCKER_NAME/collaporation-userservice:latest .
 #End of needed copy

# add line to after_success if another docker image is created above(as many docker push lines as copy till end copy code)
after_success:
 - docker login -u $DOCKER_NAME -p $DOCKER_PASSWORD
 - cd ../Eureka
 - docker push docker.io/$DOCKER_NAME/collaporation-eureka:latest
 - cd ../Gateway
 - docker push docker.io/$DOCKER_NAME/collaporation-gateway:latest
 - cd ../token
 - docker push docker.io/$DOCKER_NAME/collaporation-token:latest
 - cd ../UserService
 - docker push docker.io/$DOCKER_NAME/collaporation-userservice:latest


