language: java

jdk:
 - oraclejdk11

env:
 - MAVEN_VERSION=3.3.9

services:
 - docker

addons:
 sonarcloud:
  organization: "tomdatbenik" # the key of the org you chose at step #
  
install:
 - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"

script:
 - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=Tomdatbenik_Collapporation-Backend
 #Copy lines for a new subfolder to build and push dockerfile
 - cd $TRAVIS_BUILD_DIR/Eureka
 - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=discoveryservice
 - docker build -t docker.io/$DOCKER_NAME/collaporation-discoveryservice:latest .
 #End of needed copy
 #Copy lines for a new subfolder to build and push dockerfile
 - cd $TRAVIS_BUILD_DIR/Gateway
 - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=gatewayservice
 - docker build -t docker.io/$DOCKER_NAME/collaporation-gatewayservice:latest .
 #End of needed copy
 #Copy lines for a new subfolder to build and push dockerfile
 - cd $TRAVIS_BUILD_DIR/token
 - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=tokenservice
 - docker build -t docker.io/$DOCKER_NAME/collaporation-token:latest .
 #End of needed copy
 #Copy lines for a new subfolder to build and push dockerfile
 - cd $TRAVIS_BUILD_DIR/UserService
 - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=userservice
 - docker build -t docker.io/$DOCKER_NAME/collaporation-userservice:latest .
 #End of needed copy
 #Copy lines for a new subfolder to build and push dockerfile
 - cd $TRAVIS_BUILD_DIR/ProjectService
 - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=projectservice
 - docker build -t docker.io/$DOCKER_NAME/collaporation-projectservice:latest .
 #End of needed copy
  #Copy lines for a new subfolder to build and push dockerfile
 - cd $TRAVIS_BUILD_DIR/LikeService
 - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=like-service
 - docker build -t docker.io/$DOCKER_NAME/collaporation-likeservice:latest .
 #End of needed copy
# #Copy lines for a new subfolder to build and push dockerfile
# - cd ../TemplateService
# - mvn clean install
# - docker build -t docker.io/$DOCKER_NAME/collaporation-templateservice:latest .
# #End of needed copy

# add line to after_success if another docker image is created above(as many docker push lines as copy till end copy code)
after_success:
 - docker login -u $DOCKER_NAME -p $DOCKER_PASSWORD
 - cd $TRAVIS_BUILD_DIR/Eureka
 - docker push docker.io/$DOCKER_NAME/collaporation-eureka:latest
 - cd $TRAVIS_BUILD_DIR/Gateway
 - docker push docker.io/$DOCKER_NAME/collaporation-gateway:latest
 - cd $TRAVIS_BUILD_DIR/token
 - docker push docker.io/$DOCKER_NAME/collaporation-token:latest
 - cd $TRAVIS_BUILD_DIR/UserService
 - docker push docker.io/$DOCKER_NAME/collaporation-userservice:latest
 - cd $TRAVIS_BUILD_DIR/ProjectService
 - docker push docker.io/$DOCKER_NAME/collaporation-projectservice:latest
# - cd ../TemplateService
# - docker push docker.io/$DOCKER_NAME/collaporation-templateservice:latest


