# Start with a base image containing Java runtime
FROM openjdk:11-jdk

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port available to the world outside this container
EXPOSE 8102

# The application's jar file
ARG JAR_FILE=target/Gateway-0.0.1-SNAPSHOT.jar

RUN mkdir /collapporation
WORKDIR /collapporation

# Add the application's jar to the container
ADD ${JAR_FILE} /collapporation/Gateway-0.0.1-SNAPSHOT.jar

# Run the jar file
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-jar","/collapporation/Gateway-0.0.1-SNAPSHOT.jar"]