spring:
  profiles:
    active:
  application:
    name: like-service
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    streams:
      auto-startup: false
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8095

eureka:
  client:
    enabled: false

collapporation:
  token:
    issuer: collapperation-token-service
    publicKey: publicKey.pem
