# Start with a base image containing Java runtime
FROM openjdk:11-jdk

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port available to the world outside this container
EXPOSE 8092

# The application's jar file
ARG JAR_FILE=target/tokenservice-0.0.1-SNAPSHOT.jar

RUN mkdir /collapporation
WORKDIR /collapporation

# Add the application's jar to the container
ADD ${JAR_FILE} /collapporation/tokenservice-1.0.jar

# Run the jar file
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-jar","/collapporation/tokenservice-1.0.jar"]