spring:
  application:
    name: gateway

server:
  port: 8102

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_URI:http://localhost:8101/eureka}"
    instance:
      preferIpAddress: true

zuul:
  sensitive-headers: Cookie,Set-Cookie

collapporation:
  token:
    issuer: collapperation-token-service
    publicKey: publicKey.pem
  gateway:
    authfilter:
      matches: (/like-service/**)|(/user-service/**)