spring:
  profiles:
    active:
  application:
    name: gateway

server:
  port: 8102

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_URI:http://localhost:8101/eureka}"
    instance:
      preferIpAddress: true

---



spring:
  profiles: prod
logging:
  config: Gateway\\src\\main\\resources\\Log4J2\\Log4j2.xml
