spring:
  profiles:
    active:
  application:
    name: project-service
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    consumer:
      bootstrap-servers: tomdatbenik.nl:9092
    producer:
      bootstrap-servers: tomdatbenik.nl:9092
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8094

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_URI:http://localhost:8101/eureka}"
    instance:
      preferIpAddress: true
