spring:
  application:
    name: eureka
server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: "${EUREKA_URI:http://localhost:8101/eureka}"
    instance:
      preferIpAddress: true
