spring:
  profiles:
    active:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://80.57.128.150:3306/users?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: collapporation
    password: JJ9m]#/rPNphX>2Csd/g
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      bootstrap-servers: tomdatbenik.nl:9092
    producer:
      bootstrap-servers: tomdatbenik.nl:9092

server:
  port: 8093

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_URI:http://localhost:8101/eureka}"
    instance:
      preferIpAddress: true

collapporation:
  token:
    issuer: collapperation-token-service
    publicKey: publicKey.pem
