spring:
  profiles:
    active:
  application:
    name: project-service
  datasource:
    url: jdbc:mysql://80.57.128.150:3306/projects?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: collapporation
    password: JJ9m]#/rPNphX>2Csd/g
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    streams:
      auto-startup: true
    consumer:
      bootstrap-servers: tomdatbenik.nl:9092
    producer:
      bootstrap-servers: tomdatbenik.nl:9092
    topic: project

server:
  port: 8094

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_URI:http://localhost:8101/eureka}"
    instance:
      preferIpAddress: true
